### ISSUE TITLE
SM-G610K(ON7 2016 for KT)test

### ISSUE THREAD

**Issue by mayknight** [AnthonyKwon/android_kernel_samsung_exynos3475#1]
Wi-Fi
블루투스
소리
카메라
통신
SD 카드
USB 포트
오두 정상 
단 불안정하 녕우 이습요 (reboot)

Thank you .^_^

**Comment by AnthonyKwon** [comment]
Thanks for report, but this repository is for Galaxy Folder (exynos3475).
Please open this issue in [Ohseo-Kwon/android_kernel_samsung_exynos7870](https://github.com/Ohseo-Kwon/android_kernel_samsung_exynos7870) instead.
Thanks! :D
